#### Numpy:
        - numpy->numerical python
        - n-dimensional arrays
        - import numpy

In [1]:
import numpy as np

In [2]:
# to check the current version of numpy
np.__version__

'1.17.4'

In [3]:
# creation numpy array
# syntax:-> np.array([10,20..])
a=np.array([10,20,30,40])
print(a)

[10 20 30 40]


In [4]:
print(a.dtype)# datatype of array
print(a.ndim)# number of dimension
print(a.shape)#shape of array as tuple
print(a.size)#number of elements
print(a.itemsize)#each element size in bytes
print(a)#printing array

int32
1
(4,)
4
4
[10 20 30 40]


In [6]:
# creation 2d numpy array...
b=np.array([[10,20,30],[1,2,3]])
print(b)

[[10 20 30]
 [ 1  2  3]]


In [7]:
print(b.shape)

(2, 3)


In [8]:
# To generate arrayvalue from 0 to n using range funct
np.array(range(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.array(range(1.0,10.0))

TypeError: 'float' object cannot be interpreted as an integer

In [12]:
np.arange(1.0,10.0)

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [13]:
print(np.arange(10))
print('-----------')
print(np.arange(1.0,5.0))
print('-----------')
print(np.arange(1,10,2))
print('-------------')
print(np.arange(10,1,-3))

[0 1 2 3 4 5 6 7 8 9]
-----------
[1. 2. 3. 4.]
-----------
[1 3 5 7 9]
-------------
[10  7  4]


In [15]:
# array intialization
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
np.array([(10,20,30),(10,20,30)])

array([[10, 20, 30],
       [10, 20, 30]])

In [21]:
np.diag([3,4,5])

array([[3, 0, 0],
       [0, 4, 0],
       [0, 0, 5]])

In [27]:
np.eye((2,2))

TypeError: 'tuple' object cannot be interpreted as an integer

In [28]:
np.eye?#description about the function....

In [40]:
np.eye((3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [37]:
np.ones((2,2),dtype=int)

array([[1, 1],
       [1, 1]])

In [36]:
np.ones((3,4),int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [38]:
np.ones((2,3),np.int)

array([[1, 1, 1],
       [1, 1, 1]])

In [45]:
n1=np.full((4,3),7)
print(n1.shape)
print(n1.ndim)

(4, 3)
2


In [46]:
n2=np.full(4,7)
print(n2.ndim)

1


In [48]:
#ARITHMATIC OPERATIONS
n1=np.array([[10,20],[30,40]])
n2=np.array([[1,2],[1,2]])
print(n1)
print('----------')
print(n2)
print('-----------')
print(n1+n2)
print('------------')
print(n1-n2)
print('---------')
print(n1*n2)
print('----------')
print(n1/n2)
print('------------')
print(n1%n2)
print('------------')

[[10 20]
 [30 40]]
----------
[[1 2]
 [1 2]]
-----------
[[11 22]
 [31 42]]
------------
[[ 9 18]
 [29 38]]
---------
[[10 40]
 [30 80]]
----------
[[10. 10.]
 [30. 20.]]
------------
[[0 0]
 [0 0]]
------------


#### random

In [51]:
# To generate random number 
np.random.randint(10)

6

In [53]:
#To generate random numbers in between range.
np.random.randint(10,20,4)# here 4 is random number countn

array([18, 13, 19, 19])

In [54]:
np.random.randint(10,50,(2,3))

array([[41, 15, 34],
       [29, 32, 22]])

#### stacking
        - vstack
        - hstack

In [60]:
b1=np.random.randint(1,10,(2,2))
b2=np.random.randint(1,10,(2))
print(b1)
print('-------')
print(b2)
print('-----')
print(np.vstack((b1,b2)))
#in vstack values are added in rowwise..

[[6 7]
 [6 5]]
-------
[9 8]
-----
[[6 7]
 [6 5]
 [9 8]]


In [61]:
n3=np.random.randint(1,10,(2,2))
n4=np.random.randint(1,10,(2))
# in hstack values are append in columnwise
print(np.hstack((n3,n3)))

[[9 3 9 3]
 [3 1 3 1]]


In [62]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__doc__', '__file__', '__git_revision__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_distributor_init', '_globals', '_mat', '_pytesttester', 'abs', 'absolute', 'absolute_import

##### Array Manuplations
        - Reshape
        - Resize

In [63]:
np.arange(32).reshape(4,8)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [64]:
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [65]:
np.arange(16).reshape(5,3)

ValueError: cannot reshape array of size 16 into shape (5,3)

In [71]:
np.arange(16).reshape(4,-1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [72]:
np.arange(10).reshape(2,-1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [73]:
np.random.randint(1,20,20).reshape(4,5)

array([[ 7, 16, 11,  8,  8],
       [10, 10, 18, 15,  2],
       [15,  5, 14,  2,  8],
       [12,  1,  3, 16, 14]])

In [76]:
np.arange(4).reshape(2,2)

array([[0, 1],
       [2, 3]])

In [78]:
np.arange(16).reshape(2,2,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [79]:
np.arange(32).reshape(2,8,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29],
        [30, 31]]])

In [80]:
a=np.arange(10).reshape(2,5)
print(a)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [81]:
np.max(a)

9

In [82]:
np.min(a)

0

In [83]:
np.mean(a)

4.5

##### Indexing and slicing

In [84]:
a=np.arange(20)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [85]:
print(a[1:8])

[1 2 3 4 5 6 7]


In [86]:
print(a[5:15:2])

[ 5  7  9 11 13]


In [87]:
print(a[10:])

[10 11 12 13 14 15 16 17 18 19]


### Pandas:-
    - pandas stands for python data analysis library
    - it is open source library
    - it is mainly used for data analysis and data manipulation
    - It deals with three different data structures
    - 1.Series->like as 1-d array
    - 2.DataFrame->like as 2-d array
    - 3.Panel-> like as 3-d array
    - import pandas

In [89]:
import pandas as pd

In [90]:
# version
pd.__version__

'0.23.4'

#### Series
        -from list,numpy array
        -from dictionary

In [91]:
s1=pd.Series([10,20,30])
print(s1)

0    10
1    20
2    30
dtype: int64


In [92]:
# by index we can change the index positions
s1=pd.Series([10,20,30],index=[1,2,3])
s1

1    10
2    20
3    30
dtype: int64

In [93]:
s1=pd.Series([1,2,3],index=['A','B','C'])

In [94]:
s1

A    1
B    2
C    3
dtype: int64

In [95]:
# Accessing values
s1['A']

1

In [96]:
s1['A':'B']# stop value is including

A    1
B    2
dtype: int64

In [98]:
s1[0:3]

A    1
B    2
C    3
dtype: int64

In [99]:
# series parameter as list
s2=pd.Series(['abc','welcome','jntua'])
s2

0        abc
1    welcome
2      jntua
dtype: object

In [100]:
s2.index=[1,2,3]

In [101]:
s2

1        abc
2    welcome
3      jntua
dtype: object

In [102]:
# Series parameter as a dictionary
s4=pd.Series({'Name':'APSSDC','empid':510,'salary':300000})
s4

Name      APSSDC
empid        510
salary    300000
dtype: object

In [103]:
s4['Name']

'APSSDC'

In [105]:
# Series parameter as numpy array
import numpy as np
n1=pd.Series(np.arange(4))
n1

0    0
1    1
2    2
3    3
dtype: int32

#### DataFrame:
        - from a dictionary
        - from a numpy 2d array

In [107]:
student_marks={'Name':['ravi','Ramu','Raju'],'rollno':[510,430,320],'Maths':[10,85,70],'Telugu':[35,90,45],'English':[56,78,100]}
student_marks

{'Name': ['ravi', 'Ramu', 'Raju'],
 'rollno': [510, 430, 320],
 'Maths': [10, 85, 70],
 'Telugu': [35, 90, 45],
 'English': [56, 78, 100]}

In [108]:
# DataFrame parameter as a dictionary
d1=pd.DataFrame(student_marks)
d1

Name  rollno  Maths  Telugu  English
0  ravi     510     10      35       56
1  Ramu     430     85      90       78
2  Raju     320     70      45      100

#### read csv file
        -read_csv('filename')

In [109]:
df=pd.read_csv('marks.csv')
df

narmada  312  36  89
0    ravi  345  45  78
1    raju  567  67  89

In [110]:
df=pd.read_csv('marks.csv',header=None)
df

0    1   2   3
0  narmada  312  36  89
1     ravi  345  45  78
2     raju  567  67  89

In [115]:
df=pd.read_csv('marks.csv',names=['Name','Rollno','Maths','Telugu'])
df

Name  Rollno  Maths  Telugu
0  narmada     312     36      89
1     ravi     345     45      78
2     raju     567     67      89

In [113]:
pd.usecols?

Object `pd.usecols` not found.


In [114]:
pd.read_csv.usecols?

Object `pd.read_csv.usecols` not found.


In [ ]:
vijaykumar.b@apssdc.in
narmadha.km@apssdc.in